### PR TITLE
ENT-5498 : Added in missing actor tests. Kludged to get round java 9.

### PR DESCRIPTION
**Pull request by ghost**
Can I get away with this ?

### CODE REVIEW

**Comment by PaulHatcherR3** [comment]
Two files of interest are at the bottom of the change list. Stub_.java and module-info.java. Added these to get around the shadowing of org.objectweb.asm to co.paralleluniverse.asm.

**Review by chrisr3 — COMMENTED** [review]
So what was the problem in the end? The shading or the missing line in `module-info`?

**Comment by PaulHatcherR3** [comment]
@chrisr3 The missing line in the module-info.java . But of course I then have to add a Stub_.java file in order to introduce the co.paralleluniverse.asm package. Otherwise would not compile. This is the bit that smells a bit cheesy :) .

**Review by josephzunigadaly — APPROVED** [review]
There is too much code here to check every detail but at a high level I can see that it is code that already belongs to quasar plus the module build fix.

**Review by adelel1 — APPROVED** [review]

**Pull request merged**
