### PR TITLE
CORE-5938: Fix selection logic for which classloaders to instrument.

### PR DESCRIPTION
**Pull request by chrisr3**
Quasar is allowed to instrument classes from the bootstrap classloader, so this `null` check is wrong. Fortunately, we will already have substituted `null` for the extension classloader before arriving here, so this fix is only for "correctness".

### CODE REVIEW

**Comment by mnesbit** [comment]
Why would we allow instrumentation of bootstrap classloader?

**Comment by chrisr3** [comment]
> Why would we allow instrumentation of bootstrap classloader?

That's actually an existing option:
```java
private static final boolean allowJdkInstrumentation = isEmptyOrTrue(System.getProperty("co.paralleluniverse.fibers.allowJdkInstrumentation"));
```
However, this change doesn't have _anything_ to do with that. In fact, `loader` will _never_ be `null` at this point anyway because `null` would already have been replaced by the extension classloader. The point is this `shouldInstrument(ClassLoader)` method is _only_ about applying the exclusions from the agent's command line parameters, but has a confusing logic error.

See `JavaAgent.java`:
```java
@Override
public byte[] transform(ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws IllegalClassFormatException {
    if (loader == null) {
        loader = doPrivileged(new GetExtensionClassLoader());
    }

    if (!instrumentor.shouldInstrument(loader)) {
        return null;
    }
```

**Review by JamesHR3 — APPROVED** [review]
I seem to remember you making the equivalent change in a different PR for a different check, so it seems reasonable to bring the two in line for consistency.

**Comment by chrisr3** [comment]
> I seem to remember you making the equivalent change in a different PR for a different check, so it seems reasonable to bring the two in line for consistency.

Yes indeedy. This function was only ever intended to enforce the "exclude classloaders whose class matches <glob>" functionality. The logic to control whether we should instrument JDK classes is elsewhere. And besides, not every JDK class lives in the bootstrap classloader anyway - viz the extension classloader :shrug:.

**Pull request merged**
